"""
Video Segment Model

Video segment metadata definition
Stored in external database - material index table
"""

from datetime import datetime
from typing import Optional, List, Dict, Any
from enum import Enum
from pydantic import BaseModel, Field


class ShotType(str, Enum):
    """Shot type enumeration"""
    WIDE_FRONT = "wide_front"           # Full body front view
    WIDE_SIDE = "wide_side"             # Full body side view
    MEDIUM_FRONT = "medium_front"       # Medium shot front view
    MEDIUM_SIDE = "medium_side"         # Medium shot side view
    CLOSEUP = "closeup"                 # Close-up shot
    DETAIL = "detail"                   # Detail shot (hands, feet, etc.)


class SegmentQuality(str, Enum):
    """Segment quality level enumeration"""
    EXCELLENT = "excellent"     # Excellent (ready to use)
    GOOD = "good"               # Good (usable)
    FAIR = "fair"               # Fair (needs review)
    POOR = "poor"               # Poor (not recommended)


class VideoSegment(BaseModel):
    """
    Video segment metadata

    Stored in external database, actual video files stored in storage service
    """
    id: str = Field(..., description="Segment ID (UUID)")
    instructor_id: str = Field(..., description="Instructor ID")
    course_id: Optional[str] = Field(None, description="Course ID if associated")

    # Source file information
    source_video_path: str = Field(..., description="Source video file path")
    source_video_id: str = Field(..., description="Source video ID")

    # Time range
    start_time: float = Field(..., ge=0.0, description="Start time in seconds")
    end_time: float = Field(..., ge=0.0, description="End time in seconds")
    duration: float = Field(..., ge=0.0, description="Duration in seconds")

    # Segment file (if split)
    segment_file_path: Optional[str] = Field(None, description="Path to split segment file")

    # Visual features
    shot_type: Optional[ShotType] = Field(None, description="Shot type")
    quality_score: float = Field(0.0, ge=0.0, le=1.0, description="Quality score")
    quality_level: SegmentQuality = Field(SegmentQuality.FAIR, description="Quality level")

    # Content tags
    tags: List[str] = Field(default_factory=list, description="Tags (e.g., 'warmup', 'main_sequence')")
    action_names: List[str] = Field(default_factory=list, description="Action names list (course-specific terms)")
    intent_tags: List[str] = Field(default_factory=list, description="Intent tags (e.g., 'focus_area', 'difficulty_level')")

    # Script alignment
    script_line_ids: List[str] = Field(
        default_factory=list,
        description="Aligned script line IDs (e.g., ['line_010', 'line_018'])"
    )
    script_alignment_confidence: Optional[float] = Field(
        None,
        ge=0.0,
        le=1.0,
        description="Alignment confidence score"
    )

    # CV analysis results (JSON)
    pose_estimation: Optional[Dict[str, Any]] = Field(None, description="Pose estimation results if applicable")
    composition_features: Optional[Dict[str, Any]] = Field(None, description="Composition features")
    lighting_quality: Optional[float] = Field(None, ge=0.0, le=1.0, description="Lighting quality score")
    framing_quality: Optional[float] = Field(None, ge=0.0, le=1.0, description="Framing quality score")

    # STT results
    transcript: Optional[str] = Field(None, description="Speech-to-text transcript")
    transcript_confidence: Optional[float] = Field(None, ge=0.0, le=1.0, description="Transcription confidence score")

    # Usage statistics
    usage_count: int = Field(0, description="Usage count (how many courses use this segment)")
    last_used_at: Optional[datetime] = Field(None, description="Last usage timestamp")

    # Metadata
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)

    # Analysis job association
    analysis_job_id: Optional[str] = Field(None, description="Analysis job ID if generated by SmartCut")

    class Config:
        json_encoders = {datetime: lambda v: v.isoformat()}


class CreateVideoSegmentRequest(BaseModel):
    """Request model for creating a video segment"""
    instructor_id: str = Field(..., description="Instructor ID")
    course_id: Optional[str] = Field(None, description="Course ID")
    source_video_path: str = Field(..., description="Source video file path")
    source_video_id: str = Field(..., description="Source video ID")
    start_time: float = Field(..., ge=0.0, description="Start time in seconds")
    end_time: float = Field(..., ge=0.0, description="End time in seconds")
    tags: Optional[List[str]] = Field(default_factory=list, description="Tags")


class UpdateVideoSegmentRequest(BaseModel):
    """Request model for updating a video segment"""
    tags: Optional[List[str]] = Field(None, description="Tags")
    action_names: Optional[List[str]] = Field(None, description="Action names")
    intent_tags: Optional[List[str]] = Field(None, description="Intent tags")
    shot_type: Optional[ShotType] = Field(None, description="Shot type")
    quality_score: Optional[float] = Field(None, ge=0.0, le=1.0, description="Quality score")
    quality_level: Optional[SegmentQuality] = Field(None, description="Quality level")


class AnalyzeSegmentRequest(BaseModel):
    """Request model for analyzing a video segment"""
    analyze_cv: bool = Field(True, description="Whether to perform CV analysis")
    analyze_stt: bool = Field(True, description="Whether to perform STT analysis")
    align_to_script: bool = Field(False, description="Whether to align to script")
    script_lines: Optional[List[Dict[str, Any]]] = Field(None, description="Script lines list (if aligning)")


class BatchAnalyzeRequest(BaseModel):
    """Request model for batch analyzing video segments"""
    video_path: str = Field(..., description="Video file path")
    script_lines: Optional[List[Dict[str, Any]]] = Field(None, description="Script lines list")
    instructor_id: str = Field(..., description="Instructor ID")
    course_id: Optional[str] = Field(None, description="Course ID")
