"""
Video Segment Model

Video segment metadata definition
Stored in external database - material index table
"""

from datetime import datetime
from typing import Optional, List, Dict, Any
from enum import Enum
from pydantic import BaseModel, Field


class ShotType(str, Enum):
    """Shot type enumeration"""
    WIDE_FRONT = "wide_front"           # Full body front view
    WIDE_SIDE = "wide_side"             # Full body side view
    MEDIUM_FRONT = "medium_front"       # Medium shot front view
    MEDIUM_SIDE = "medium_side"         # Medium shot side view
    CLOSEUP = "closeup"                 # Close-up shot
    DETAIL = "detail"                   # Detail shot (hands, feet, etc.)


class SegmentQuality(str, Enum):
    """Segment quality level enumeration"""
    EXCELLENT = "excellent"     # Excellent (ready to use)
    GOOD = "good"               # Good (usable)
    FAIR = "fair"               # Fair (needs review)
    POOR = "poor"               # Poor (not recommended)


class VideoSegment(BaseModel):
    """
    Video segment metadata

    Stored in external database, actual video files stored in storage service
    """
    id: str = Field(..., description="Segment ID (UUID)")
    instructor_id: str = Field(..., description="Instructor ID")
    course_id: Optional[str] = Field(None, description="Course ID if associated")

    # Source file information
    source_video_path: str = Field(..., description="Source video file path")
    source_video_id: str = Field(..., description="Source video ID")

    # Time range
    start_time: float = Field(..., ge=0.0, description="Start time in seconds")
    end_time: float = Field(..., ge=0.0, description="End time in seconds")
    duration: float = Field(..., ge=0.0, description="Duration in seconds")

    # Segment file (if split)
    segment_file_path: Optional[str] = Field(None, description="Path to split segment file")

    # Visual features
    shot_type: Optional[ShotType] = Field(None, description="Shot type")
    quality_score: float = Field(0.0, ge=0.0, le=1.0, description="Quality score")
    quality_level: SegmentQuality = Field(SegmentQuality.FAIR, description="Quality level")

    # Content tags
    tags: List[str] = Field(default_factory=list, description="Tags (e.g., 'warmup', 'main_sequence')")
    action_names: List[str] = Field(default_factory=list, description="Action names list (course-specific terms)")
    intent_tags: List[str] = Field(default_factory=list, description="Intent tags (e.g., 'focus_area', 'difficulty_level')")

    # Script alignment
    script_line_ids: List[str] = Field(
        default_factory=list,
        description="Aligned script line IDs (e.g., ['line_010', 'line_018'])"
    )
    script_alignment_confidence: Optional[float] = Field(
        None,
        ge=0.0,
        le=1.0,
        description="Alignment confidence score"
    )

    # CV analysis results (JSON)
    pose_estimation: Optional[Dict[str, Any]] = Field(None, description="Pose estimation results if applicable")
    composition_features: Optional[Dict[str, Any]] = Field(None, description="Composition features")
    lighting_quality: Optional[float] = Field(None, ge=0.0, le=1.0, description="Lighting quality score")
    framing_quality: Optional[float] = Field(None, ge=0.0, le=1.0, description="Framing quality score")

    # STT results
    transcript: Optional[str] = Field(None, description="Speech-to-text transcript")
    transcript_confidence: Optional[float] = Field(None, ge=0.0, le=1.0, description="Transcription confidence score")

    # Usage statistics
    usage_count: int = Field(0, description="Usage count (how many courses use this segment)")
    last_used_at: Optional[datetime] = Field(None, description="Last usage timestamp")

    # Metadata
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)

    # Analysis job association
    analysis_job_id: Optional[str] = Field(None, description="Analysis job ID if generated by SmartCut")

    class Config:
        json_encoders = {datetime: lambda v: v.isoformat()}


class CreateVideoSegmentRequest(BaseModel):
    """創建視頻片段請求"""
    instructor_id: str = Field(..., description="講師 ID")
    course_id: Optional[str] = Field(None, description="課程 ID")
    source_video_path: str = Field(..., description="源視頻文件路徑")
    source_video_id: str = Field(..., description="源視頻 ID")
    start_time: float = Field(..., ge=0.0, description="開始時間（秒）")
    end_time: float = Field(..., ge=0.0, description="結束時間（秒）")
    tags: Optional[List[str]] = Field(default_factory=list, description="標籤")


class UpdateVideoSegmentRequest(BaseModel):
    """更新視頻片段請求"""
    tags: Optional[List[str]] = Field(None, description="標籤")
    action_names: Optional[List[str]] = Field(None, description="動作名稱")
    intent_tags: Optional[List[str]] = Field(None, description="意圖標籤")
    shot_type: Optional[ShotType] = Field(None, description="鏡頭類型")
    quality_score: Optional[float] = Field(None, ge=0.0, le=1.0, description="品質分數")
    quality_level: Optional[SegmentQuality] = Field(None, description="品質等級")


class AnalyzeSegmentRequest(BaseModel):
    """分析片段請求"""
    analyze_cv: bool = Field(True, description="是否進行 CV 分析")
    analyze_stt: bool = Field(True, description="是否進行 STT 分析")
    align_to_script: bool = Field(False, description="是否對齊到腳本")
    script_lines: Optional[List[Dict[str, Any]]] = Field(None, description="腳本行列表（如果對齊）")


class BatchAnalyzeRequest(BaseModel):
    """批量分析請求"""
    video_path: str = Field(..., description="視頻文件路徑")
    script_lines: Optional[List[Dict[str, Any]]] = Field(None, description="腳本行列表")
    instructor_id: str = Field(..., description="講師 ID")
    course_id: Optional[str] = Field(None, description="課程 ID")
