import { describe, expect, it } from 'vitest';

describe('generate-capability-ui-context-registry', () => {
  it('generates a build-adapter registry with the required contract header', async () => {
    const module = await import('./generate-capability-ui-context-registry.mjs');
    const source = module.buildCapabilityUiContextRegistrySource([
      'performance_direction',
      'ig',
    ]);

    expect(source).toContain('Generated by web-console/scripts/generate-capability-ui-context-registry.mjs');
    expect(source).toContain('build adapter for component loading only');
    expect(source).toContain('"ig": () => import(\'./capability-ui-contexts/ig\')');
    expect(source).toContain('"performance_direction": () => import(\'./capability-ui-contexts/performance_direction\')');
    expect(source).not.toContain('staticHostCapabilityCodes');
    expect(source).not.toContain('WorkspaceToolRail');
    expect(source).not.toContain('workspace_tools');
  });
});
