"""Constants for visual acceptance follow-up request artifacts."""

VISUAL_ACCEPTANCE_FOLLOWUP_ARTIFACT_KIND = "visual_acceptance_followup_request"
VISUAL_ACCEPTANCE_FOLLOWUP_PLAYBOOK_CODE = "visual_acceptance_followup"
VISUAL_ACCEPTANCE_FOLLOWUP_DISPATCH_ARTIFACT_KIND = "visual_acceptance_followup_dispatch"
VISUAL_ACCEPTANCE_FOLLOWUP_DISPATCH_PLAYBOOK_CODE = "visual_acceptance_followup_dispatch"
VISUAL_ACCEPTANCE_SCENE_REVIEW_ARTIFACT_KIND = "visual_acceptance_scene_review_request"
VISUAL_ACCEPTANCE_SCENE_REVIEW_PLAYBOOK_CODE = "visual_acceptance_scene_review"
FOLLOWUP_REQUEST_STATE_READY = "ready"
FOLLOWUP_REQUEST_STATE_BLOCKED = "blocked"
FOLLOWUP_REQUEST_STATE_DISPATCHED = "dispatched"
FOLLOWUP_REQUEST_STATE_COMPLETED = "completed"
FOLLOWUP_REQUEST_STATE_SUPERSEDED = "superseded"
VALID_FOLLOWUP_REQUEST_STATES = {
    FOLLOWUP_REQUEST_STATE_READY,
    FOLLOWUP_REQUEST_STATE_BLOCKED,
    FOLLOWUP_REQUEST_STATE_DISPATCHED,
    FOLLOWUP_REQUEST_STATE_COMPLETED,
    FOLLOWUP_REQUEST_STATE_SUPERSEDED,
}
_MAX_ARTIFACT_ID_LENGTH = 64
