export const DEFAULT_TOKEN_HEADER_NAMES = [
  'cf-access-jwt-assertion',
  'cf_authorization',
  'cf-authorization',
];

export const ALLOWLIST_EMAIL_ENV = 'MOBILE_WORKBENCH_GATEWAY_ALLOWLIST_EMAILS';
export const ALLOWLIST_GROUP_ENV = 'MOBILE_WORKBENCH_GATEWAY_ALLOWLIST_GROUPS';
export const WORKSPACE_ALLOWLIST_ENV = 'MOBILE_WORKBENCH_GATEWAY_WORKSPACE_ALLOWLIST';
export const PUBLIC_ORIGIN_ENV = 'MOBILE_WORKBENCH_GATEWAY_PUBLIC_ORIGIN';
export const JWT_AUDIENCE_ENV = 'MOBILE_WORKBENCH_GATEWAY_JWT_AUDIENCE';
export const JWT_ISSUER_ENV = 'MOBILE_WORKBENCH_GATEWAY_JWT_ISSUER';
export const JWT_CLOCK_SKEW_ENV = 'MOBILE_WORKBENCH_GATEWAY_JWT_CLOCK_SKEW_SECONDS';
export const JWT_PUBLIC_KEY_ENV = 'MOBILE_WORKBENCH_GATEWAY_JWT_PUBLIC_KEY';
export const JWT_PUBLIC_KEY_FILE_ENV = 'MOBILE_WORKBENCH_GATEWAY_JWT_PUBLIC_KEY_FILE';
export const JWT_REQUIRE_SIGNATURE_VERIFICATION_ENV = 'MOBILE_WORKBENCH_GATEWAY_REQUIRE_SIGNATURE_VERIFICATION';

export const MAX_CLOCK_SKEW_SECONDS_DEFAULT = 30;
export const JWT_ALGORITHMS = new Set(['RS256', 'RS384', 'RS512', 'PS256', 'PS384', 'PS512']);
export const JWT_VERIFY_ALGORITHMS = {
  RS256: 'RSA-SHA256',
  RS384: 'RSA-SHA384',
  RS512: 'RSA-SHA512',
  PS256: 'RSA-SHA256',
  PS384: 'RSA-SHA384',
  PS512: 'RSA-SHA512',
};

export const GATEWAY_CONTROL_CAPABILITY_CODE = 'mindscape_cloud_integration';
export const GATEWAY_CONTROL_COMPONENT_CODE = 'MindscapeMobileWorkbenchGatewayPage';
export const READ_ONLY_GATEWAY_METHODS = ['GET', 'HEAD', 'OPTIONS'];
