import importlib.util
import sys
import types
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
BACKEND_ROOT = REPO_ROOT / "backend"
if str(BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(BACKEND_ROOT))

import backend.app as backend_app
from backend.app.models.object_runtime import ObjectInstanceRecord, ObjectRef

sys.modules["app"] = backend_app


def load_object_runtime_module() -> Any:
    workspace_dir = REPO_ROOT / "backend" / "app" / "routes" / "core" / "workspace"
    package_name = "backend.app.routes.core.workspace"
    if package_name not in sys.modules:
        workspace_package = types.ModuleType(package_name)
        workspace_package.__path__ = [str(workspace_dir)]
        sys.modules[package_name] = workspace_package

    module_path = workspace_dir / "object_runtime.py"
    module_name = "backend.app.routes.core.workspace.object_runtime_action_plan_test_module"
    spec = importlib.util.spec_from_file_location(module_name, module_path)
    module = importlib.util.module_from_spec(spec)
    assert spec is not None and spec.loader is not None
    sys.modules[module_name] = module
    spec.loader.exec_module(module)
    return module


object_runtime_module = load_object_runtime_module()


def install_object_runtime_module_alias() -> None:
    sys.modules["backend.app.routes.core.workspace.object_runtime"] = object_runtime_module


def make_ref(owner_pack: str, object_kind: str, object_id: str) -> ObjectRef:
    return ObjectRef(
        uri=f"mindscape://{owner_pack}/{object_kind}/{object_id}",
        owner_pack=owner_pack,
        object_kind=object_kind,
        object_id=object_id,
        workspace_id="ws_demo",
    )


def build_role_assignments() -> list[dict[str, Any]]:
    return [
        {"role": "source", "ref": make_ref("ig", "reference", "ref_001").model_dump()},
        {
            "role": "target",
            "ref": make_ref(
                "performance_direction",
                "storyboard_scene",
                "pd_session_1:latest:sc02",
            ).model_dump(),
        },
        {
            "role": "character",
            "ref": make_ref("character_training", "character_card", "card_chacto").model_dump(),
        },
    ]


def make_reels_output_record(object_id: str = "gra_invoke_001") -> ObjectInstanceRecord:
    return ObjectInstanceRecord(
        ref=make_ref("performance_direction", "generated_reels_asset", object_id),
        title="Invoked reels asset",
        summary_text="Generated by invoke endpoint.",
        mention_tokens=[f"@reels_asset:{object_id}"],
        mention_text="invoked reels asset",
    )


class FakeCatalogRegistry:
    def __init__(self, *, include_affordance: bool = True):
        self.include_affordance = include_affordance

    def get_entry(self, owner_pack: str, object_kind: str) -> dict[str, Any]:
        payload: dict[str, Any] = {
            "owner_pack": owner_pack,
            "object_kind": object_kind,
            "display_name": object_kind.replace("_", " ").title(),
            "id_field": "id",
            "affordances": [],
        }
        if self.include_affordance and object_kind == "storyboard_scene":
            payload["affordances"] = [
                {
                    "verb": "generate_reels_asset",
                    "label": "Generate reels asset",
                    "description": "Generate an asset into a storyboard scene.",
                    "object_kinds": ["storyboard_scene"],
                    "input_schema": {"type": "object"},
                    "output_schema": {"type": "object"},
                    "required_roles": ["source", "target", "character"],
                    "write_modes": ["staged"],
                    "planner_backend": "capabilities.performance_direction.services.aol:plan_reels_asset",
                    "executor_backend": "capabilities.performance_direction.services.aol:execute_reels_asset",
                }
            ]
        return payload


async def fake_ensure_workspace_exists(workspace_id: str) -> None:
    assert workspace_id == "ws_demo"


class CaptureObjectInstanceStore:
    def __init__(self, captured_records: list[ObjectInstanceRecord]):
        self.captured_records = captured_records

    def upsert_many(self, workspace_id: str, records: list[ObjectInstanceRecord]) -> int:
        assert workspace_id == "ws_demo"
        self.captured_records.extend(records)
        return len(records)


class CaptureRelationStore:
    def __init__(self, captured_relations: list[Any]):
        self.captured_relations = captured_relations

    def upsert_many(self, workspace_id: str, relations: list[Any]) -> int:
        assert workspace_id == "ws_demo"
        self.captured_relations.extend(relations)
        return len(relations)


class CaptureTasksStore:
    def __init__(self, captured_tasks: list[Any]):
        self.captured_tasks = captured_tasks

    def get_task_by_execution_id(self, execution_id: str) -> None:
        return None

    def create_task(self, task: Any) -> Any:
        self.captured_tasks.append(task)
        return task
