from backend.app.models.object_runtime import ObjectInstanceRecord
from backend.app.services.object_action_closure_wiring import (
    close_object_action_from_execution_result,
)
from backend.tests.object_action_planning_runtime_test_support import (
    CaptureObjectInstanceStore,
    CaptureRelationStore,
    build_role_assignments,
    install_object_runtime_module_alias,
    make_ref,
    object_runtime_module,
)


def test_runtime_closure_wiring_indexes_structured_execution_outputs(monkeypatch):
    captured_outputs = []
    captured_relations = []

    monkeypatch.setattr(
        object_runtime_module,
        "_get_object_instance_registry_store",
        lambda: CaptureObjectInstanceStore(captured_outputs),
    )
    monkeypatch.setattr(
        object_runtime_module,
        "_get_object_relation_registry_store",
        lambda: CaptureRelationStore(captured_relations),
    )
    install_object_runtime_module_alias()

    output_record = ObjectInstanceRecord(
        ref=make_ref("performance_direction", "generated_reels_asset", "gra_exec_001"),
        title="Runtime generated reels asset",
        summary_text="Generated by a completed meeting tool execution.",
        mention_tokens=["@reels_asset:gra_exec_001"],
        mention_text="runtime generated reels asset",
        affordance_verbs=["review_generated_reels_asset"],
    )

    closure = close_object_action_from_execution_result(
        workspace_id="ws_demo",
        execution_id="exec_001",
        inputs={
            "meeting_id": "meeting_demo",
            "object_action_plan": {
                "request_plan": {
                    "action_plan_id": "oap_exec_001",
                    "affordance_verb": "generate_reels_asset",
                },
                "role_assignments": build_role_assignments(),
            },
        },
        execution_result={
            "outputs": {
                "object_action_closure": {
                    "output_records": [output_record.model_dump()],
                }
            }
        },
    )

    assert closure["status"] == "succeeded"
    assert closure["action_plan_id"] == "oap_exec_001"
    assert closure["indexed_output_count"] == 1
    assert closure["indexed_relation_count"] == 3
    assert captured_outputs[0].ref.object_id == "gra_exec_001"
    assert [relation.relation_kind for relation in captured_relations] == [
        "generated_from_source",
        "landed_in",
        "generated_with_character",
    ]


def test_runtime_closure_wiring_marks_planned_execution_without_outputs_as_skipped():
    closure = close_object_action_from_execution_result(
        workspace_id="ws_demo",
        execution_id="exec_002",
        inputs={
            "object_action_plan": {
                "request_plan": {
                    "action_plan_id": "oap_exec_002",
                    "affordance_verb": "generate_reels_asset",
                },
            },
        },
        execution_result={"outputs": {"message": "No addressable output emitted."}},
    )

    assert closure == {
        "status": "skipped",
        "reason": "no_output_records",
        "action_plan_id": "oap_exec_002",
        "execution_id": "exec_002",
    }
