"""
Shared LLM utilities
Low-level utility functions for LLM API calls
"""

import logging
from typing import Dict, List, Optional, Any

from backend.app.services.llm.workspace_routed_chat import (
    chat_completion_with_workspace_route,
)

logger = logging.getLogger(__name__)


def build_prompt(
    system_prompt: Optional[str] = None,
    user_prompt: Optional[str] = None,
    context: Optional[Dict[str, Any]] = None,
    examples: Optional[List[Dict[str, str]]] = None
) -> List[Dict[str, str]]:
    """
    Build LLM message list

    Args:
        system_prompt: System prompt
        user_prompt: User prompt
        context: Context information (optional)
        examples: Example conversations (optional)

    Returns:
        Formatted message list that can be directly passed to LLM API
    """
    messages = []

    # System prompt
    if system_prompt:
        messages.append({
            "role": "system",
            "content": system_prompt
        })

    # Add context information if available
    if context:
        context_text = _format_context(context)
        if context_text:
            messages.append({
                "role": "system",
                "content": f"[CONTEXT]\n{context_text}\n[/CONTEXT]"
            })

    # Example conversations
    if examples:
        for example in examples:
            if "role" in example and "content" in example:
                messages.append(example)

    # User prompt
    if user_prompt:
        messages.append({
            "role": "user",
            "content": user_prompt
        })

    return messages


def _format_context(context: Dict[str, Any]) -> str:
    """Format context information as text"""
    parts = []
    for key, value in context.items():
        if isinstance(value, (str, int, float, bool)):
            parts.append(f"{key}: {value}")
        elif isinstance(value, dict):
            parts.append(f"{key}: {_format_dict(value)}")
        elif isinstance(value, list):
            parts.append(f"{key}: {', '.join(str(v) for v in value)}")
    return "\n".join(parts)


def _format_dict(d: Dict[str, Any], indent: int = 0) -> str:
    """Recursively format dictionary"""
    parts = []
    prefix = "  " * indent
    for key, value in d.items():
        if isinstance(value, dict):
            parts.append(f"{prefix}{key}:")
            parts.append(_format_dict(value, indent + 1))
        else:
            parts.append(f"{prefix}{key}: {value}")
    return "\n".join(parts)


async def call_llm(
    messages: Optional[List[Dict[str, str]]] = None,
    llm_provider: Any = None,
    model: Optional[str] = None,
    temperature: float = 0.7,
    max_tokens: Optional[int] = None,
    *,
    prompt: Optional[List[Dict[str, str]]] = None,
    model_name: Optional[str] = None,
    workspace_id: Optional[str] = None,
    profile_id: Optional[str] = None,
    route_context: Optional[Dict[str, Any]] = None,
    stage_name: Optional[str] = None,
    purpose: str = "llm_utils.call_llm",
    risk_level: str = "read",
) -> Dict[str, Any]:
    """
    Call LLM API

    Args:
        messages: Message list (generated by build_prompt)
        llm_provider: LLM provider object (LLMProvider or LLMProviderManager)
        model: Model name (optional)
        temperature: Temperature parameter
        max_tokens: Maximum token count (optional)

    Returns:
        Dict containing:
            - text: LLM response text
            - usage: Token usage information (if available)
    """
    try:
        normalized_messages = messages if messages is not None else prompt
        if normalized_messages is None:
            raise Exception("No messages provided")
        if llm_provider is None:
            raise Exception("No LLM provider available")

        resolved_model_name = model_name or model
        provider = None
        llm_provider_manager = None

        from backend.app.shared.llm_provider_helper import (
            get_llm_provider_from_settings,
            resolve_llm_selection,
        )

        if hasattr(llm_provider, "get_llm_manager") and hasattr(
            llm_provider, "get_llm_provider"
        ):
            llm_provider_manager = llm_provider
        elif hasattr(llm_provider, "get_provider"):
            try:
                selection = resolve_llm_selection(
                    model_name=resolved_model_name,
                    default_model="gpt-4o-mini",
                    purpose=purpose,
                )
                resolved_model_name = selection.model_name
                provider = get_llm_provider_from_settings(
                    llm_provider,
                    model_name=resolved_model_name,
                    default_model="gpt-4o-mini",
                    purpose=purpose,
                )
            except ValueError as e:
                logger.warning(
                    "LLM provider not available for model %s: %s",
                    resolved_model_name,
                    e,
                )
                raise Exception(f"No LLM provider available: {e}")
        else:
            provider = llm_provider
            if not resolved_model_name:
                resolved_model_name = resolve_llm_selection(
                    model_name=None,
                    default_model="gpt-4o-mini",
                    purpose=purpose,
                ).model_name

        if provider is None and llm_provider_manager is None:
            raise Exception("No LLM provider available")

        if provider is not None:
            logger.info(
                "LLM provider type: %s, has chat_completion: %s",
                type(provider),
                hasattr(provider, "chat_completion"),
            )
            if not hasattr(provider, "chat_completion"):
                error_msg = (
                    f"Provider {type(provider)} does not have chat_completion method. "
                    f"Provider: {provider}"
                )
                logger.error(error_msg)
                raise Exception(error_msg)

        response = await chat_completion_with_workspace_route(
            messages=normalized_messages,
            workspace_id=workspace_id,
            profile_id=profile_id,
            model=resolved_model_name,
            max_tokens=max_tokens,
            provider=provider,
            llm_provider_manager=llm_provider_manager,
            route_context=route_context,
            purpose=purpose,
            stage_name=stage_name,
            risk_level=risk_level,
            temperature=temperature,
        )

        response_text = (
            response.get("content", "")
            if isinstance(response, dict)
            else str(response or "")
        )

        usage = {}
        if provider is not None and hasattr(provider, "last_usage"):
            usage = provider.last_usage

        provider_class = provider.__class__.__name__ if provider is not None else None
        return {
            "text": response_text,
            "content": response_text,
            "usage": usage,
            "model_name": resolved_model_name,
            "provider_class": provider_class,
        }
    except Exception as e:
        logger.error(f"LLM call failed: {e}")
        raise


def extract_json_from_text(text: str) -> Optional[Dict[str, Any]]:
    """
    Extract JSON object from text, handling truncated JSON from MAX_TOKENS.

    Args:
        text: Text containing JSON (may be truncated)

    Returns:
        Extracted JSON object, or None if failed
    """
    import json
    import re

    def _find_balanced_json(candidate_text: str) -> Optional[str]:
        """Return first balanced JSON object substring (handles deeply nested braces)."""
        start = candidate_text.find("{")
        while start != -1:
            depth = 0
            in_string = False
            escape = False
            for i in range(start, len(candidate_text)):
                ch = candidate_text[i]
                if in_string:
                    if escape:
                        escape = False
                    elif ch == "\\":
                        escape = True
                    elif ch == '"':
                        in_string = False
                else:
                    if ch == '"':
                        in_string = True
                    elif ch == "{":
                        depth += 1
                    elif ch == "}":
                        depth -= 1
                        if depth == 0:
                            return candidate_text[start:i + 1]
            start = candidate_text.find("{", start + 1)
        return None

    # Try to parse the entire text directly
    try:
        return json.loads(text)
    except:
        pass

    # Remove markdown code blocks if present
    text_clean = text.strip()
    if text_clean.startswith("```json"):
        text_clean = text_clean[7:]
    if text_clean.startswith("```"):
        text_clean = text_clean[3:]
    if text_clean.endswith("```"):
        text_clean = text_clean[:-3]
    text_clean = text_clean.strip()

    # Try to parse cleaned text
    try:
        return json.loads(text_clean)
    except:
        pass

    # Try to locate a balanced JSON object even with nested structures
    balanced_json = _find_balanced_json(text_clean)
    if balanced_json:
        try:
            return json.loads(balanced_json)
        except:
            pass

    # Try to extract JSON object (prefer larger/more complete matches)
    json_pattern = r'\{[^{}]*(?:\{[^{}]*\}[^{}]*)*\}'
    matches = re.findall(json_pattern, text_clean, re.DOTALL)

    # Sort by length (descending) to prefer larger/more complete JSON objects
    matches = sorted(matches, key=len, reverse=True)

    for match in matches:
        try:
            parsed = json.loads(match)
            # Prefer objects with "tasks" key if it exists
            if isinstance(parsed, dict) and "tasks" in parsed:
                return parsed
        except:
            continue

    # If no match with "tasks" key, try all matches
    for match in matches:
        try:
            return json.loads(match)
        except:
            continue

    # Last resort: try to extract partial JSON from truncated response
    # This handles cases where JSON is cut off mid-structure (e.g., MAX_TOKENS)
    if text_clean.startswith("{"):
        try:
            # Try to extract completed key-value pairs even if JSON is truncated
            # Look for patterns like "key": "value" or "key": value
            partial_json = {}

            # Find all completed key-value pairs before truncation
            # Pattern: "key": (value|"string")
            import re
            kv_pattern = r'"([^"]+)":\s*("(?:[^"\\]|\\.)*"|[^,}\]]+?)(?=,\s*"|,|\s*})'
            matches = re.finditer(kv_pattern, text_clean, re.DOTALL)

            for match in matches:
                key = match.group(1)
                value_str = match.group(2).strip()

                # Try to parse the value
                try:
                    # If it's a quoted string, unquote it
                    if value_str.startswith('"') and value_str.endswith('"'):
                        value = json.loads(value_str)  # This handles escaped quotes
                    # If it's a number, parse it
                    elif value_str.replace('.', '').replace('-', '').isdigit():
                        value = float(value_str) if '.' in value_str else int(value_str)
                    # If it's boolean or null
                    elif value_str in ['true', 'false', 'null']:
                        value = json.loads(value_str)
                    # If it's an array or object, try to parse it
                    elif value_str.startswith('[') or value_str.startswith('{'):
                        try:
                            value = json.loads(value_str)
                        except:
                            continue  # Skip incomplete arrays/objects
                    else:
                        continue  # Skip unparseable values

                    partial_json[key] = value
                except:
                    continue

            # If we extracted at least lens_id, return partial JSON
            if "lens_id" in partial_json and len(partial_json) > 0:
                logger.warning(f"Extracted partial JSON from truncated response: {list(partial_json.keys())}")
                return partial_json
        except Exception as e:
            logger.debug(f"Failed to extract partial JSON: {e}")

    return None
