"""
Workspace governance API compatibility entrypoint.
"""

from backend.app.services.governance.memory_impact_graph_contract import (
    MemoryImpactGraphResponse,
)

from .workspace_governance_core.metrics_routes import (
    _query_cost_usage_from_db,
    _query_governance_decisions_from_db,
    _query_governance_metrics_from_db,
)
from .workspace_governance_core.router import router
from .workspace_governance_core.schemas import (
    ArtifactLandingDrilldownSummary,
    CostMonitoringData,
    EvidenceCoverageSummary,
    ExecutionTraceDrilldownSummary,
    GoalLedgerProjectionSummary,
    GovernanceDecision,
    GovernanceDecisionsResponse,
    GovernanceMetricsData,
    MemoryEdgeSummary,
    MemoryEvidenceSummary,
    MemoryTransitionRequest,
    MemoryTransitionResponse,
    MemoryVersionSummary,
    PersonalKnowledgeProjectionSummary,
    SuccessorDraftSuggestionSummary,
    TransitionCueSummary,
    TransitionReasonSuggestions,
    WorkflowEvidenceHealthSessionSummary,
    WorkflowEvidenceHealthSummaryResponse,
    WorkspaceMemoryDetailResponse,
    WorkspaceMemoryItemSummary,
    WorkspaceMemoryListResponse,
)
from .workspace_governance_core.serializers import (
    _build_artifact_landing_drilldown,
    _build_evidence_coverage,
    _build_execution_trace_drilldown,
    _evidence_display_name,
    _evidence_priority,
    _path_exists,
    _select_primary_evidence,
    _serialize_goal_projection,
    _serialize_memory_edge,
    _serialize_memory_evidence,
    _serialize_memory_version,
    _serialize_personal_knowledge_projection,
    _serialize_workspace_memory_item,
)
from .workspace_governance_core.stores import (
    _get_goal_ledger_store,
    _get_meeting_session_store,
    _get_memory_edge_store,
    _get_memory_evidence_link_store,
    _get_memory_impact_graph_read_model,
    _get_memory_item_store,
    _get_memory_promotion_service,
    _get_memory_version_store,
    _get_personal_knowledge_store,
    _get_store,
    _load_workspace_memory_item,
)
from .workspace_governance_core.transition_suggestions import (
    _build_successor_draft_suggestion,
    _build_transition_cues,
    _build_transition_reason_suggestions,
)
from .workspace_governance_core.workflow_health import (
    _classify_workflow_evidence_diagnostics,
    _serialize_workflow_evidence_health_session,
)

__all__ = [
    "router",
    "MemoryImpactGraphResponse",
    "GovernanceDecision",
    "GovernanceDecisionsResponse",
    "CostMonitoringData",
    "GovernanceMetricsData",
    "MemoryTransitionRequest",
    "MemoryTransitionResponse",
    "WorkspaceMemoryItemSummary",
    "WorkspaceMemoryListResponse",
    "MemoryVersionSummary",
    "MemoryEvidenceSummary",
    "MemoryEdgeSummary",
    "PersonalKnowledgeProjectionSummary",
    "GoalLedgerProjectionSummary",
    "EvidenceCoverageSummary",
    "TransitionCueSummary",
    "SuccessorDraftSuggestionSummary",
    "TransitionReasonSuggestions",
    "ArtifactLandingDrilldownSummary",
    "ExecutionTraceDrilldownSummary",
    "WorkspaceMemoryDetailResponse",
    "WorkflowEvidenceHealthSessionSummary",
    "WorkflowEvidenceHealthSummaryResponse",
    "_get_memory_item_store",
    "_get_memory_version_store",
    "_get_memory_evidence_link_store",
    "_get_memory_edge_store",
    "_get_memory_promotion_service",
    "_get_personal_knowledge_store",
    "_get_goal_ledger_store",
    "_get_meeting_session_store",
    "_get_memory_impact_graph_read_model",
    "_load_workspace_memory_item",
    "_get_store",
    "_serialize_workspace_memory_item",
    "_serialize_memory_version",
    "_path_exists",
    "_build_artifact_landing_drilldown",
    "_build_execution_trace_drilldown",
    "_serialize_memory_evidence",
    "_serialize_memory_edge",
    "_serialize_personal_knowledge_projection",
    "_serialize_goal_projection",
    "_evidence_display_name",
    "_build_evidence_coverage",
    "_evidence_priority",
    "_select_primary_evidence",
    "_build_transition_cues",
    "_build_successor_draft_suggestion",
    "_build_transition_reason_suggestions",
    "_classify_workflow_evidence_diagnostics",
    "_serialize_workflow_evidence_health_session",
    "_query_governance_decisions_from_db",
    "_query_cost_usage_from_db",
    "_query_governance_metrics_from_db",
]
