from __future__ import annotations

from pathlib import Path


DEFAULT_WINDOW_SEC = 2.0
MOTION_INGEST_MIN_WINDOW_INTERVAL_MS = 500.0
DEFAULT_SAMPLE_FPS = 5.0
DEFAULT_MAX_SAMPLES = 10
DEFAULT_STATUS_EVERY_SEC = 30.0
DEFAULT_ROLLUP_EVERY_SEC = 60.0
DEFAULT_API_TIMEOUT_SEC = 30.0
DEFAULT_CONTROL_API_TIMEOUT_SEC = 30.0
DEFAULT_ROLLUP_API_TIMEOUT_SEC = 30.0
DEFAULT_CLOSEOUT_API_TIMEOUT_SEC = 30.0
DEFAULT_API_RETRY_COUNT = 3
DEFAULT_API_RETRY_BACKOFF_SEC = 0.5
DEFAULT_APPEND_QUEUE_MAX_SIZE = 64
DEFAULT_APPEND_ACK_RECOVERY_BACKOFF_SEC = 8.0
DEFAULT_APPEND_ACK_RECOVERY_MAX_SEC = 130.0
DEFAULT_STREAM_READ_TIMEOUT_SEC = 10.0
DEFAULT_STREAM_RECONNECT_BACKOFF_SEC = 1.0
DEFAULT_FORMAL_STREAM_RECONNECT_MAX_ATTEMPTS = 8
DEFAULT_STREAM_READ_FAILURE_THRESHOLD = 2
DEFAULT_STREAM_GAP_HOLDOVER_SEC = 0.0
DEFAULT_STREAM_GAP_HOLDOVER_CONFIDENCE_CAP = 0.75
DEFAULT_CAPTURE_BACKEND = "ffmpeg"
DEFAULT_FRAME_WIDTH = 640
DEFAULT_FRAME_HEIGHT = 360
DEFAULT_AVFOUNDATION_FRAMERATE = 60.0
DEFAULT_FFMPEG_REALTIME_INPUT = False
DEFAULT_FFMPEG_BIN = "/opt/homebrew/bin/ffmpeg"
DEFAULT_MODEL_ASSET_PATH = (
    Path(__file__).resolve().parents[2]
    / "web-console"
    / "public"
    / "mediapipe"
    / "models"
    / "pose_landmarker_lite.task"
)
