// Generated by web-console/scripts/generate-capability-ui-context-registry.mjs.
// This file is a build adapter for component loading only. It must not be used
// as a product route whitelist, installed capability list, or workspace tool registry.

import type { CapabilityComponentsContext } from './capability-ui-context-types';

type CapabilityContextModule = {
  default: CapabilityComponentsContext;
};

type CapabilityContextLoader = () => Promise<CapabilityContextModule>;

const contextLoaders: Record<string, CapabilityContextLoader> = {
  "comfyui_runtime": () => import('./capability-ui-contexts/comfyui_runtime'),
};

function capabilityCodeVariants(capabilityCode: string): string[] {
  const variants = new Set<string>();
  const trimmed = capabilityCode.trim();
  if (trimmed) {
    variants.add(trimmed);
    variants.add(trimmed.replace(/-/g, '_'));
    variants.add(trimmed.replace(/_/g, '-'));
  }
  return Array.from(variants);
}

export async function loadRegisteredCapabilityComponentsContext(
  capabilityCode: string,
): Promise<{ capabilityCode: string; context: CapabilityComponentsContext } | null> {
  for (const variant of capabilityCodeVariants(capabilityCode)) {
    const loader = contextLoaders[variant];
    if (!loader) {
      continue;
    }
    const module = await loader();
    return {
      capabilityCode: variant,
      context: module.default,
    };
  }
  return null;
}

export function getRegisteredCapabilityComponentContextCodes(): string[] {
  return Object.keys(contextLoaders);
}
